---
- hosts: dockerubuntu
  become: yes
  vars_files:
    - vars/group_vars/docker.yml
      
  tasks:
  - name: run "apt-get update"
    apt:
       update_cache: yes

  - name: ensure older versions of docker are uninstalled
    apt:
       name: docker
       state: absent

  - name: ensure older versions of docker are uninstalled
    apt:
       name: docker-engine
       state: absent

  - name: install prerequisite for https repositories
    apt:
       name: apt-transport-https  
       state: present

  - name: install prerequisite for https repositories
    apt:
       name: ca-certificates
       state: present

  - name: install prerequisite for https repositories
    apt:
       name: software-properties-common 
       state: present
   
  - name: add docker repo gpg key
    apt_key: 
      id: "{{ docker_key_id }}"
      url: "{{ docker_url }}/ubuntu/gpg"      

  - name: add docker repository for ubuntu distribution
    apt_repository: 
      repo: "{{ docker_repo_ubuntu }}"
      state: present

  - name: install docker
    apt:
       name: "{{ docker_version }}"
       state: present

